// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpendingTrackerApi.Data;

#nullable disable

namespace spending_tracker_api.Migrations
{
    [DbContext(typeof(SpendingDbContext))]
    partial class SpendingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("SpendingTrackerApi.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            Name = "Caleb Expenses"
                        });
                });

            modelBuilder.Entity("SpendingTrackerApi.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Shopping",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Travel",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Big Boy Job",
                            Type = "Income"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Health Insurance",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Dental Insurance",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Federal & State Income Tax",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Medicare & Social Security Tax",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "HSA",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Emergency Fund",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "401(k)",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 11,
                            Name = "Entertainment",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 12,
                            Name = "Groceries",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 13,
                            Name = "Drinks",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 14,
                            Name = "Roth IRA",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 15,
                            Name = "Long Term Investments",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 16,
                            Name = "Short Term Savings",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 17,
                            Name = "Gas",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 18,
                            Name = "Clothes & Shoes",
                            Type = "Expense"
                        },
                        new
                        {
                            CategoryId = 19,
                            Name = "Presents",
                            Type = "Income"
                        },
                        new
                        {
                            CategoryId = 20,
                            Name = "Eating Out",
                            Type = "Expense"
                        });
                });

            modelBuilder.Entity("SpendingTrackerApi.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("SpendingTrackerApi.Models.Transaction", b =>
                {
                    b.HasOne("SpendingTrackerApi.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SpendingTrackerApi.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SpendingTrackerApi.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SpendingTrackerApi.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
